### ISSUE TITLE
Create Login Component

### ISSUE THREAD

**Issue by drew-garcia** [drew-garcia/profit-pulse-client#2]
### Description:
- Implement a login component that handles authentication.

### Tasks:
- [x] Creates a new component named `Login`.
- [x] Implement authentication logic.
- [x] Create unit test for this component
- [x] Add `/login` route
